#!/bin/bash

set -euo pipefail

if [[ "$#" -ne 2 ]]; then
    echo "Usage: $0 VERSION SHA256" >&2
    exit 64
fi

version="$1"
checksum="$2"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid version: $version" >&2
    exit 64
fi
if [[ ! "$checksum" =~ ^[0-9a-f]{64}$ ]]; then
    echo "Invalid SHA256: $checksum" >&2
    exit 64
fi

cat <<EOF
# typed: strict
# frozen_string_literal: true

# This file was generated by the XPlay release workflow. DO NOT EDIT.
cask "xplay" do
  version "$version"
  sha256 "$checksum"

  url "https://github.com/mobilepur/xplay/releases/download/v#{version}/XPlay.tar.gz"
  name "XPlay"
  desc "Build and launch Xcode projects from the menu bar"
  homepage "https://github.com/mobilepur/xplay"

  depends_on macos: :sequoia

  app "XPlay.app"

  postflight do
    path = "#{appdir}/XPlay.app"
    quarantine = system_command(
      "/usr/bin/xattr",
      args:         ["-p", "com.apple.quarantine", path],
      must_succeed: false,
      print_stderr: false,
    )
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", path] if quarantine&.success?
  end

  uninstall quit: "de.mobilepur.XPlay"

  zap trash: [
    "~/Library/Caches/XPlay",
    "~/Library/Preferences/de.mobilepur.XPlay.plist",
    "~/Library/Saved Application State/de.mobilepur.XPlay.savedState",
  ]

  caveats "XPlay requires a full Xcode installation to build projects and run simulators."
end
EOF
